### ISSUE TITLE
Add region URL on pack config

### ISSUE THREAD

**Issue by piellick** [StackStorm-Exchange/stackstorm-opsgenie#12]
Hi,
is it possible to add "opsgenie" region on config for european user ? ;-) 
https://docs.opsgenie.com/docs/european-service-region

**Comment by arm4b** [comment]
It's probably possible if api.opsgenie.com referenced in https://github.com/StackStorm-Exchange/stackstorm-opsgenie/blob/master/actions/lib/actions.py supports that.

As packs are managed mostly by community and opensource. It would be a good first issue for someone to contribute this enhancement :wink:

**Comment by jjm** [comment]
I'm happy to do this, should not take too long.

@piellick You happy to test when I've got the PR open? I'll add a `region` config option that defaults to the US.

**Comment by jjm** [comment]
I've opened a PR, seems I still have merge permissions and we don't need peer review....

I'll give it some time for @piellick to test and merge tomorrow if nothing comes up.

**Comment by piellick** [comment]
I everyone ! Too efficient for me :-D 
i will not have time to test until next week but the only difference between US and EU tenant is : 
```
US : https://api.opsgenie.com
EU: https://api.eu.opsgenie.com
```
