### ISSUE TITLE
New Maintainer Required

### ISSUE THREAD

**Issue by jjm** [StackStorm-Exchange/stackstorm-opsgenie#6]
I’ve recently changed jobs and it’s very unlikely I’ll have a chance to make use of  this pack again. 

If someone would like take over that would be great.

**Comment by LindsayHill** [comment]
@MeralBusraTekinsen since you did a recent major overhaul of this pack, is this something you would be interested in?

**Comment by MeralBusraTekinsen** [comment]
Sure. But ı didn't get the problem when I configured pack again with OpsGenie API key. Can you give some details about problem?

**Comment by LindsayHill** [comment]
This is not a problem as such. This is a request for a new pack maintainer, as @jjm is no longer in a position to act as such.

There are no hard requirements to act as a pack maintainer. You get given write access to this repo, and you can review & merge PRs. You can add yourself to `pack.yaml` if you like.

It's not entirely up to you though. The rest of the StackStorm team can continue to help. It just means that if someone does submit a PR, or you yourself have a small fix to make, you can merge it yourself, without needing someone from the StackStorm team to do it.

**Comment by MeralBusraTekinsen** [comment]
Sure, I can be the new maintainer. Thanks!

**Comment by LindsayHill** [comment]
Cool! I'll invite you to the account. You will then have full control with merging PRs, etc. No real rules apply, just follow the basics - make sure tests are passing before merge, etc.

And don't worry if you don't have time, the rest of us will keep an eye on it too
